/* ЗГЕНЕРОВАНО scripts/build-editor-fonts.py — руками не правити.
 *
 * Які з наших шрифтів справді мають кириличні гліфи. Це факт про
 * файли в public/editor-fonts/, а не про те, що пропонує підбірка:
 * FONT_DATA[].cyr відповідає на друге питання, і саме тому вони вже
 * розходилися. Українським текстом у родині, якої тут немає, друк
 * вийде системним шрифтом — про це попереджає перелік перед
 * оформленням і перевірка макетів в адмінці.
 */
export const FONTS_WITH_CYRILLIC: ReadonlySet<string> = new Set([
  'Alegreya',
  'Alegreya SC',
  'Amatic SC',
  'Bad Script',
  'Bellota',
  'Bitter',
  'Caveat',
  'Comfortaa',
  'Comforter',
  'Comforter Brush',
  'Cormorant',
  'Cormorant Garamond',
  'Cormorant Infant',
  'Cormorant SC',
  'Cormorant Unicase',
  'Dela Gothic One',
  'EB Garamond',
  'El Messiri',
  'Exo 2',
  'Fira Sans',
  'Forum',
  'Gabriela',
  'Great Vibes',
  'Inter',
  'Jost',
  'Kelly Slab',
  'Kurale',
  'Ledger',
  'Literata',
  'Lobster',
  'Lora',
  'Manrope',
  'Marck Script',
  'Marmelad',
  'Merriweather',
  'Montserrat',
  'Neucha',
  'Noto Sans',
  'Noto Serif',
  'Nunito',
  'Old Standard TT',
  'Open Sans',
  'Oranienbaum',
  'Oswald',
  'PT Serif',
  'Pacifico',
  'Pangolin',
  'Philosopher',
  'Playfair Display',
  'Playfair Display SC',
  'Podkova',
  'Poiret One',
  'Press Start 2P',
  'Prosto One',
  'Raleway',
  'Roboto',
  'Rubik',
  'Ruslan Display',
  'Russo One',
  'Seymour One',
  'Shantell Sans',
  'Source Sans 3',
  'Spectral',
  'Stalinist One',
  'Tektur',
  'Tenor Sans',
  'Ubuntu',
  'Unbounded',
  'Underdog',
  'Vollkorn',
  'Wix Madefor Text',
  'Yeseva One',
]);

/**
 * Усі родини, файли яких ми віддаємо самі.
 *
 * Родина поза цим переліком друкується системним шрифтом, хай би що
 * стояло в макеті: у контейнері Railway немає ні Georgia, ні будь-чого
 * іншого з Windows. Це не те саме, що «немає кирилиці» — там ідеться
 * про частину тексту, а тут про весь.
 */
export const FONTS_IN_PACK: ReadonlySet<string> = new Set([
  'Abril Fatface',
  'Alegreya',
  'Alegreya SC',
  'Amatic SC',
  'Architects Daughter',
  'Bad Script',
  'Bebas Neue',
  'Bellota',
  'Bitter',
  'Caveat',
  'Cinzel',
  'Cinzel Decorative',
  'Comfortaa',
  'Comforter',
  'Comforter Brush',
  'Cormorant',
  'Cormorant Garamond',
  'Cormorant Infant',
  'Cormorant SC',
  'Cormorant Unicase',
  'Crimson Text',
  'DM Sans',
  'Dancing Script',
  'Dela Gothic One',
  'EB Garamond',
  'El Messiri',
  'Exo 2',
  'Fira Sans',
  'Forum',
  'Gabriela',
  'Great Vibes',
  'Handlee',
  'Indie Flower',
  'Inter',
  'Josefin Sans',
  'Jost',
  'Kalam',
  'Kelly Slab',
  'Kurale',
  'Lato',
  'Ledger',
  'Libre Baskerville',
  'Literata',
  'Lobster',
  'Lora',
  'Manrope',
  'Marck Script',
  'Marmelad',
  'Merriweather',
  'Montserrat',
  'Neucha',
  'Noto Sans',
  'Noto Serif',
  'Nunito',
  'Old Standard TT',
  'Open Sans',
  'Oranienbaum',
  'Oswald',
  'Outfit',
  'PT Serif',
  'Pacifico',
  'Pangolin',
  'Patrick Hand',
  'Permanent Marker',
  'Philosopher',
  'Playfair Display',
  'Playfair Display SC',
  'Plus Jakarta Sans',
  'Podkova',
  'Poiret One',
  'Poppins',
  'Press Start 2P',
  'Prosto One',
  'Raleway',
  'Reenie Beanie',
  'Righteous',
  'Roboto',
  'Rubik',
  'Ruslan Display',
  'Russo One',
  'Sacramento',
  'Satisfy',
  'Schibsted Grotesk',
  'Seymour One',
  'Shadows Into Light',
  'Shantell Sans',
  'Source Sans 3',
  'Spectral',
  'Stalinist One',
  'Tektur',
  'Tenor Sans',
  'Ubuntu',
  'Unbounded',
  'Underdog',
  'Vollkorn',
  'Wix Madefor Text',
  'Yeseva One',
]);
